# Generated by Django 5.0.6 on 2024-05-30 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallaCurricular', '0002_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='carrerasList', to='mallaCurricular.facultad'),
            preserve_default=False,
        ),
    ]
