# Generated by Django 5.0.6 on 2024-05-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallaCurricular', '0004_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
    ]
