# Generated by Django 5.0.6 on 2024-05-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallaCurricular', '0007_carrera_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='modalidad',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial'), ('Distancia', 'Distancia')], default='Presencial', max_length=20),
        ),
    ]
