# Generated by Django 5.0.6 on 2024-05-30 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mallaCurricular', '0008_alter_carrera_modalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='modalidad',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Semipresencial', 'Semipresencial'), ('Distancia', 'Distancia')], default='Presencial', max_length=20),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='nombre',
            field=models.CharField(help_text='Nombre de la facultad', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='siglas',
            field=models.CharField(blank=True, help_text='Siglas de la facultad', max_length=10),
        ),
    ]
